src/Web/ModernRecrut.MVC/Controllers/DocumentsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using ModernRecrut.MVC.Areas.Identity.Data;
using ModernRecrut.MVC.Interfaces;
using ModernRecrut.MVC.Models.DTO;
using System.Security.Claims;

namespace ModernRecrut.MVC.Controllers
{
    [Authorize]
    public class DocumentsController : Controller
    {
        private readonly IDocumentsService _documentsService;
        private readonly IConfiguration _config;
      
        public DocumentsController(IDocumentsService documentsService, IConfiguration config) 
        {
            _documentsService = documentsService;
            _config = config;         
        }
        // GET: DocumentsController
        public async Task<ActionResult> Index()
        {
            var id = User.FindFirstValue(ClaimTypes.NameIdentifier);
            
            var documents = await _documentsService.ObtenirDocumentsSelonId(Guid.Parse(id));
            return View(documents);
        }

        // GET: DocumentsController/Details/5
        public async Task<ActionResult> Details(string nomFichier)
        {
            var lien =await _documentsService.LireFichier(nomFichier.Split(":")[0].Trim());
            return Redirect(lien);
        }

        // GET: DocumentsController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: DocumentsController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(RequeteFichier fichier)
        {
            var id = User.FindFirstValue(ClaimTypes.NameIdentifier);
            fichier.UtilisateurID = Guid.Parse(id);
            if (!fichier.FileDetails.FileName.EndsWith(".pdf") && !fichier.FileDetails.FileName.EndsWith(".docx"))
                ModelState.AddModelError("FileDetails", "Vous pouvez téléchargez juste des fichiers au formats pdf et word");
            if (fichier.FileDetails.Length > _config.GetValue<long>("TailleLimite"))
                ModelState.AddModelError("FileDetails", "Fichier trop volumineux");
            if (ModelState.IsValid)
            {
                await _documentsService.EnregistrerDocument(fichier);

                return RedirectToAction(nameof(Index));             
            }
            return View();        
        }

        // GET: DocumentsController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: DocumentsController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: DocumentsController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: DocumentsController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(string nomFichier)
        {
            await _documentsService.SupprimerDocument(nomFichier.Split(":")[0].Trim());
            return RedirectToAction(nameof(Index));
        }
    }
}

src/Web/ModernRecrut.MVC/Controllers/FavorisController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using ModernRecrut.MVC.Interfaces;
using ModernRecrut.MVC.Models;
using ModernRecrut.MVC.Models.DTO;
using ModernRecrut.MVC.Services;
using System.Net;

namespace ModernRecrut.MVC.Controllers
{
    public class FavorisController : Controller
    {
        private readonly IFavorisService _favorisService;
        private readonly IOffresEmploiService _offresEmploiService;
        private string ipAddress;
        public FavorisController(IFavorisService favorisService, IOffresEmploiService offresEmploiService)
        {
            _favorisService = favorisService;
            _offresEmploiService = offresEmploiService;
        }

        // GET: FavorisController
        public async Task<ActionResult> Index()
        {
            RecupererAdresseIp();

            Favoris favoris = await _favorisService.ObtenirTout(ipAddress);
            return View(favoris);
        }

        public async Task<ActionResult> Details(Guid id)
        {
            var offreEmploi = await _offresEmploiService.ObtenirOffreEmploiSelonId(id);
            return View(offreEmploi);
        }

        // POST: FavorisController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(OffreEmploi offre)
        {
            RecupererAdresseIp();

            if (ModelState.IsValid)
            {
                RequeteAjoutFavorite requeteFavorite = new RequeteAjoutFavorite { Cle = ipAddress, OffreEmploiID = offre.Id };
                await _favorisService.AjouterFavorite(requeteFavorite);
            }
            
            return RedirectToAction("Index", "OffresEmploi");
        }

        // GET: FavorisController/Delete/5
        public async Task<ActionResult> Delete(Guid id)
        {
            RecupererAdresseIp();

            var favoris = await _favorisService.ObtenirTout(ipAddress);
            var offreASupprimer = favoris.Contenu.FirstOrDefault(o => o.Id == id);
            return View(offreASupprimer);
        }

        // POST: FavorisController/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(Guid id)
        {
            RecupererAdresseIp();

            if (ModelState.IsValid)
            {
                await _favorisService.SupprimerFavorite(ipAddress, id);
            }

            return RedirectToAction(nameof(Index));
        }

        private void RecupererAdresseIp()
        {
            ipAddress = Request.HttpContext.Connection.RemoteIpAddress.ToString();

            //En local, on obtient toujours l'adresse loopback IPv6 compressée
            if (ipAddress == "::1")
                ipAddress = Dns.GetHostEntry(Dns.GetHostName()).AddressList[0].MapToIPv4().ToString();

        }
    }
}

src/Web/ModernRecrut.MVC/Controllers/NotesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using ModernRecrut.MVC.Areas.Identity.Data;
using ModernRecrut.MVC.Interfaces;
using ModernRecrut.MVC.Models;
using ModernRecrut.MVC.Models.DTO;
using System.Security.Claims;

namespace ModernRecrut.MVC.Controllers
{
    [Authorize(Roles = "Admin, RH")]
    public class NotesController : Controller
    {
        private readonly INotesService _notesService;
        private readonly IPostulationsService _postulationsSerivce;
        private readonly IOffresEmploiService _emploisService;
		private readonly UserManager<Utilisateur> _gestionnaireUtilisateur;
		public NotesController(INotesService notesService, IPostulationsService postulationsSerivce,UserManager<Utilisateur> gestionnaireUtilisateur, IOffresEmploiService emploisService) 
        {
            _notesService = notesService;
            _postulationsSerivce = postulationsSerivce;
            _gestionnaireUtilisateur = gestionnaireUtilisateur;
            _emploisService = emploisService;
        }
        // GET: NotesController
        public async Task<ActionResult> Index()
        {
            var postulations = await _postulationsSerivce.ObtenirPostulations();

            
            if (postulations.Any())
            {
                for (int i = 0; i < postulations.Count; i++)
                {

                    postulations[i].OffreEmploi = await _emploisService.ObtenirOffreEmploiSelonId(postulations[i].OffreEmploiID);
                    postulations[i].Candidat = await _gestionnaireUtilisateur.FindByIdAsync(postulations[i].CandidatID.ToString());
                }
            }

            return View(postulations.Where(e => e.OffreEmploi != null));
        }
        public async Task<ActionResult> MesNotes()
        {
            var emetteurID = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var emetteur = await _gestionnaireUtilisateur.FindByIdAsync(emetteurID);

            var nomEmeteur = emetteur.Nom + " " + emetteur.Prenom;
            var notes = await _notesService.ObtenirNotes();
            return View(notes.Where(n => n.NomEmetteur == nomEmeteur));
        }
        // GET: NotesController/Details/5
        public async Task<ActionResult> Details(Guid id)
        {
            var note = await _notesService.ObtenirNoteSelonId(id);
            return View(note);
        }

        // GET: NotesController/Create
        public async Task< ActionResult> Create(Guid id)
        {
			var emetteurID = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var emetteur = await _gestionnaireUtilisateur.FindByIdAsync(emetteurID);
        
            var nomEmeteur = emetteur.Nom + " " + emetteur.Prenom;
			RequeteNote note = new RequeteNote { PostulationID = id, NomEmetteur = nomEmeteur};
            return View(note);
        }

        // POST: NotesController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(RequeteNote requeteNote)
        {
            

            if (ModelState.IsValid)
            {
                await _notesService.AjouterNote(requeteNote);
                return RedirectToAction(nameof(MesNotes));
            }
            return View();
        }

        // GET: NotesController/Edit/5
        public async Task<ActionResult> Edit(Guid id)
        {
            var note = await _notesService.ObtenirNoteSelonId(id);
            return View(note);
        }

        // POST: NotesController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(Note note)
        {
            if (ModelState.IsValid)
            {
                await _notesService.ModifierNote(note);
                return RedirectToAction(nameof(MesNotes));
            }
            return View(note);
        }

        // GET: NotesController/Delete/5
        public async Task<ActionResult> Delete(Guid id)
        {
            var note = await _notesService.ObtenirNoteSelonId(id);
            return View(note);
        }

        // POST: NotesController/Delete/5
        [HttpPost,ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(Guid id)
        {
            
            await _notesService.SupprimerNote(id);
            return RedirectToAction(nameof(MesNotes));
        }
    }
}

src/Web/ModernRecrut.MVC/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using ModernRecrut.MVC.Areas.Identity.Data

@inject SignInManager<Utilisateur> SignInManager
@inject UserManager<Utilisateur> UserManager
<script >
    window.addEventListener('DOMContentLoaded', function () {
        var modeSombre = localStorage.getItem('modeSombre');
        if (modeSombre === 'dark') {
            document.documentElement.setAttribute('data-bs-theme', 'dark');
        } else {
            document.documentElement.setAttribute('data-bs-theme', 'light');
        }
    });
</script>
<!DOCTYPE html>
<html lang="en" data-bs-theme="light">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ModernRecrut</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ModernRecrut.MVC.styles.css" asp-append-version="true" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand " asp-area="" asp-controller="Home" asp-action="Index" >
                   ModernRecrut
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Accueil</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="OffresEmploi" asp-action="Index">Offres d'emploi</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Favoris" asp-action="Index">Favoris</a>
                        </li>
                     
                        @if (SignInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Documents" asp-action="Index">Documents</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Postulations" asp-action="Index">Mes Postulations</a>
                            </li>
                        }
                       
                        
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Notes" asp-action="Index">Liste des postulations</a>
                            </li>
                        
                        @if (SignInManager.IsSignedIn(User) && User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Autorisations" asp-action="Index">Gestion des autorisations</a>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial"/>
                       <div class="p-2 border rounded">
                        <div class="form-check form-switch" id="btnSwitch">
                            <input class="form-check-input" type="checkbox" role="switch" id="flexSwitchCheckDefault"
                            <label class="form-check-label" for="flexSwitchCheckDefault">
                               
                               
                                    <svg xmlns="http://www.w3.org/2000/svg" id="light" width="16" height="16" fill="currentColor" class="bi bi-brightness-high" viewBox="0 0 16 16">
                                        <path d="M8 11a3 3 0 1 1 0-6 3 3 0 0 1 0 6zm0 1a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z" />
                                    </svg>
                                
                          
                                
                            </label> 
                        </div>
 
                    </div> 
                 
                     
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; <script>document.write(new Date().getFullYear());</script> - ModernRecrut
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
   <script type="text/javascript">
       

       document.getElementById('btnSwitch').addEventListener('click', () => {
           if (document.documentElement.getAttribute('data-bs-theme') == 'dark') {
               document.documentElement.setAttribute('data-bs-theme', 'light')
                localStorage.setItem('modeSombre', 'light');
           }
           else {
               document.documentElement.setAttribute('data-bs-theme','dark')
                localStorage.setItem('modeSombre', 'dark');
           }
       })
   </script> 
    @await RenderSectionAsync("Scripts", required: false)

</body>
</html>