src/Web/ModernRecrut.MVC/Models/Note.cs
using System.ComponentModel;

namespace ModernRecrut.MVC.Models
{
    public class Note
    {
        public Guid Id { get; set; }
        public string? Description { get; set; }
        [DisplayName("Nom émetteur")]
        public string? NomEmetteur { get; set; }
        public Guid PostulationID { get; set; }
    }
}

src/Web/ModernRecrut.MVC/Controllers/NotesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using ModernRecrut.MVC.Areas.Identity.Data;
using ModernRecrut.MVC.Interfaces;
using ModernRecrut.MVC.Models;
using ModernRecrut.MVC.Models.DTO;
using System.Security.Claims;

namespace ModernRecrut.MVC.Controllers
{
    [Authorize(Roles = "Admin, RH")]
    public class NotesController : Controller
    {
        private readonly INotesService _notesService;
        private readonly IPostulationsService _postulationsSerivce;
        private readonly IOffresEmploiService _emploisService;
		private readonly UserManager<Utilisateur> _gestionnaireUtilisateur;
		public NotesController(INotesService notesService, IPostulationsService postulationsSerivce,UserManager<Utilisateur> gestionnaireUtilisateur, IOffresEmploiService emploisService) 
        {
            _notesService = notesService;
            _postulationsSerivce = postulationsSerivce;
            _gestionnaireUtilisateur = gestionnaireUtilisateur;
            _emploisService = emploisService;
        }
        // GET: NotesController
        public async Task<ActionResult> Index()
        {
            var postulations = await _postulationsSerivce.ObtenirPostulations();

            
            if (postulations.Any())
            {
                for (int i = 0; i < postulations.Count; i++)
                {

                    postulations[i].OffreEmploi = await _emploisService.ObtenirOffreEmploiSelonId(postulations[i].OffreEmploiID);
                    postulations[i].Candidat = await _gestionnaireUtilisateur.FindByIdAsync(postulations[i].CandidatID.ToString());
                }
            }

            return View(postulations.Where(e => e.OffreEmploi != null));
        }
        public async Task<ActionResult> MesNotes()
        {
            var emetteurID = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var emetteur = await _gestionnaireUtilisateur.FindByIdAsync(emetteurID);

            var nomEmeteur = emetteur.Nom + " " + emetteur.Prenom;
            var notes = await _notesService.ObtenirNotes();
            return View(notes.Where(n => n.NomEmetteur == nomEmeteur));
        }
        // GET: NotesController/Details/5
        public async Task<ActionResult> Details(Guid id)
        {
            var note = await _notesService.ObtenirNoteSelonId(id);
            return View(note);
        }

        // GET: NotesController/Create
        public async Task< ActionResult> Create(Guid id)
        {
			var emetteurID = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var emetteur = await _gestionnaireUtilisateur.FindByIdAsync(emetteurID);
        
            var nomEmeteur = emetteur.Nom + " " + emetteur.Prenom;
			RequeteNote note = new RequeteNote { PostulationID = id, NomEmetteur = nomEmeteur};
            return View(note);
        }

        // POST: NotesController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(RequeteNote requeteNote)
        {
            

            if (ModelState.IsValid)
            {
                await _notesService.AjouterNote(requeteNote);
                return RedirectToAction(nameof(MesNotes));
            }
            return View();
        }

        // GET: NotesController/Edit/5
        public async Task<ActionResult> Edit(Guid id)
        {
            var note = await _notesService.ObtenirNoteSelonId(id);
            return View(note);
        }

        // POST: NotesController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(Note note)
        {
            if (ModelState.IsValid)
            {
                await _notesService.ModifierNote(note);
                return RedirectToAction(nameof(MesNotes));
            }
            return View(note);
        }

        // GET: NotesController/Delete/5
        public async Task<ActionResult> Delete(Guid id)
        {
            var note = await _notesService.ObtenirNoteSelonId(id);
            return View(note);
        }

        // POST: NotesController/Delete/5
        [HttpPost,ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(Guid id)
        {
            
            await _notesService.SupprimerNote(id);
            return RedirectToAction(nameof(MesNotes));
        }
    }
}

src/Web/ModernRecrut.MVC/Controllers/PostulationsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using ModernRecrut.MVC.Areas.Identity.Data;
using ModernRecrut.MVC.Interfaces;
using ModernRecrut.MVC.Models;
using ModernRecrut.MVC.Models.DTO;
using System.Security.Claims;

namespace ModernRecrut.MVC.Controllers
{
    [Authorize]
    public class PostulationsController : Controller
    {
        private readonly IPostulationsService _postulationService;
        private readonly IDocumentsService _documentsService;
        private readonly IOffresEmploiService _emploisService;
        private readonly UserManager<Utilisateur> _userManager;
        private readonly INotesService _notesService;

        public PostulationsController(IPostulationsService postulationService, IDocumentsService documentsService, IOffresEmploiService offresEmploiService, UserManager<Utilisateur> userManager, INotesService notesService)
        {
            _postulationService = postulationService;
            _documentsService = documentsService;
            _emploisService = offresEmploiService;
            _userManager = userManager;
            _notesService = notesService;

        }

        [Authorize(Roles = "Admin, Candidat")]
        public async Task<IActionResult> Index()
        {
            var candidatID = Guid.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));

            var postulations = await _postulationService.ObtenirPostulations();
            var postulationsCandidat = postulations.Where(p => p.CandidatID == candidatID).ToList();

            if (postulationsCandidat.Any())
            {
                for (int i = 0; i < postulationsCandidat.Count; i++)
                {

                    postulationsCandidat[i].OffreEmploi = await _emploisService.ObtenirOffreEmploiSelonId(postulationsCandidat[i].OffreEmploiID);
                    postulationsCandidat[i].Candidat = await _userManager.FindByIdAsync(postulationsCandidat[i].CandidatID.ToString());
                }
            }

            return View(postulationsCandidat);
        }

        [Authorize(Roles = "Admin, Candidat,RH")]
        public async Task<ActionResult> Details(Guid id)
        {
            var postulation = await _postulationService.ObtenirPostulationSelonId(id);
            postulation.OffreEmploi = await _emploisService.ObtenirOffreEmploiSelonId(postulation.OffreEmploiID);
            postulation.Candidat = await _userManager.FindByIdAsync(postulation.CandidatID.ToString());
            var notes = await _notesService.ObtenirNotes();
            postulation.Notes = notes.Where(e => e.PostulationID == postulation.Id).ToList();

            return View(postulation);
        }

        [Authorize(Roles = "Admin, Candidat")]
        public ActionResult Create(Guid id)
        {
            RequetePostulation postulation = new RequetePostulation { OffreEmploiID = id, CandidatID = Guid.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier)), DateDisponibilite = DateTime.Now.Date };
            return View(postulation);
        }

        [Authorize(Roles = "Admin, Candidat")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(RequetePostulation requetePostulation)
        {
            var documentsCandidat = await _documentsService.ObtenirDocumentsSelonId(requetePostulation.CandidatID);
            if (!documentsCandidat.Any(d => d.Contains("CV")))
                ModelState.AddModelError(string.Empty, "Un CV est obligatoire pour postuler. Veuillez déposer au préalable un CV dans votre espace Documents");

            if (!documentsCandidat.Any(d => d.Contains("LETTREDEMOTIVATION")))
                ModelState.AddModelError(string.Empty, "Une lettre de motivation est obligatoire pour postuler. Veuillez déposer au préalable une lettre de motivation dans votre espace Documents");

            var postulations = await _postulationService.ObtenirPostulations();
            if (postulations.Where(p => p.CandidatID == requetePostulation.CandidatID).Any(p => p.OffreEmploiID == requetePostulation.OffreEmploiID))
                ModelState.AddModelError(string.Empty, "Vous avez déjà postulé à cette offre d'emploi");

            if (requetePostulation.PretentionSalariale > 150000)
                ModelState.AddModelError("PretentionSalariale", "Votre prétention salariale est au-delà de nos limites");

            if (requetePostulation.PretentionSalariale <= 0)
                ModelState.AddModelError("PretentionSalariale", "Veuillez saisir une valeur valide pour le salaire");

            DateTime dateLimite = DateTime.Now.AddDays(45);
            if (requetePostulation.DateDisponibilite <= DateTime.Now || requetePostulation.DateDisponibilite > DateTime.Now.AddDays(45))
                ModelState.AddModelError("DateDisponibilite", $"La date de disponibilité doit être supérieure à la date du jour et inférieure à {dateLimite.ToString("yyyy-MM-dd")}");

            if (ModelState.IsValid)
            {
                await _postulationService.AjouterPostulation(requetePostulation);
                return RedirectToAction(nameof(Index));
            }
            return View(requetePostulation);

        }

        [Authorize(Roles = "Admin, Candidat")]
        public async Task<ActionResult> Edit(Guid id)
        {
            var postulation = await _postulationService.ObtenirPostulationSelonId(id);
            if (postulation == null)
                return NotFound();

            return View(postulation);
        }

        [Authorize(Roles = "Admin, Candidat")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(Postulation postulation)
        {
            var postulationAmodifier = await _postulationService.ObtenirPostulationSelonId(postulation.Id);
            if (postulationAmodifier.DateDisponibilite > DateTime.Now.AddDays(5) || postulationAmodifier.DateDisponibilite < DateTime.Now.AddDays(-5))
            {
                ModelState.AddModelError("DateDisponibilite", "Vous ne pouvez pas modifier la date de disponibilité pour cette postulation");
                return View(postulation);
            }

            if (postulation.PretentionSalariale > 150000)
                ModelState.AddModelError("PretentionSalariale", "Votre prétention salariale est au-delà de nos limites");

            if (postulation.PretentionSalariale <= 0)
                ModelState.AddModelError("PretentionSalariale", "Veuillez saisir une valeur valide pour le salaire");

            DateTime dateLimite = DateTime.Now.AddDays(45);
            if (postulation.DateDisponibilite <= DateTime.Now || postulation.DateDisponibilite > DateTime.Now.AddDays(45))
                ModelState.AddModelError("DateDisponibilite", $"La date de disponibilité doit être supérieure à la date du jour et inférieure à {dateLimite.ToString("yyyy-MM-dd")}");

            if (ModelState.IsValid)
            {
                await _postulationService.ModifierPostulation(postulation);
                return RedirectToAction(nameof(Index));
            }
            return View(postulation);
        }

        [Authorize(Roles = "Admin, Candidat")]
        public async Task<ActionResult> Delete(Guid id)
        {
            var postulation = await _postulationService.ObtenirPostulationSelonId(id);
            return View(postulation);
        }

        [Authorize(Roles = "Admin, Candidat")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(Guid id)
        {
            var postulationAsupprimer = await _postulationService.ObtenirPostulationSelonId(id);
            if (postulationAsupprimer.DateDisponibilite > DateTime.Now.AddDays(5) || postulationAsupprimer.DateDisponibilite < DateTime.Now.AddDays(-5))
                ModelState.AddModelError("DateDisponibilite", "Vous ne pouvez pas supprimer cette postulation");

            await _postulationService.SupprimerPostulation(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

src/Web/ModernRecrut.MVC/Views/Notes/Create.cshtml
@model ModernRecrut.MVC.Models.DTO.RequeteNote

@{
    ViewData["Title"] = "Create";
}

<h1>Ajouter une note</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
				<textarea asp-for="Description" class="text-danger"> </textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
             
                <input asp-for="PostulationID" class="form-control" hidden />
                <input asp-for="NomEmetteur" class="form-control" hidden />
            </br>
            <div class="form-group">
                <input type="submit" value="Ajouter" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Retourner à la liste</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

src/Web/ModernRecrut.MVC/Views/Notes/Delete.cshtml
@model ModernRecrut.MVC.Models.Note

@{
    ViewData["Title"] = "Delete";
}

<h1>Suppression de la note</h1>

<h3>Êtes-vous sûr de vouloir supprimer la note ?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.NomEmetteur)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.NomEmetteur)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PostulationID)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PostulationID)
        </dd>


    </dl>

    <form asp-action="Delete">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="Id" />
        <br />
        <input type="submit" value="Supprimer" class="btn btn-danger" /> |
        <a asp-action="Index">Retourner à la liste</a>
    </form>
</div>

src/Web/ModernRecrut.MVC/Views/Notes/Details.cshtml
@model ModernRecrut.MVC.Models.Note

@{
    ViewData["Title"] = "Details";
}

<h1>Détails de la note</h1>

<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.NomEmetteur)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.NomEmetteur)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PostulationID)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PostulationID)
        </dd>
       
    </dl>
</div>

<div>
    @Html.ActionLink("Modifier", "Edit", new {  id = Model.Id  }) |
    <a asp-action="Index">Retourner à la liste</a>
</div>

src/Web/ModernRecrut.MVC/Views/Notes/Edit.cshtml
@model ModernRecrut.MVC.Models.Note

@{
    ViewData["Title"] = "Edit";
}

<h1>Modification de la note</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <div style="font-weight:bold;font-size:large">@Html.DisplayNameFor(model => model.Id) : @Html.DisplayFor(model => model.Id)</div>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
				<textarea asp-for="Description" class="form-control" > </textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            
            <input asp-for="NomEmetteur" class="form-control" hidden />
            <input asp-for="PostulationID" class="form-control" hidden />
            
            </br>
            <div class="form-group">
                <input type="submit" value="Modifier" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Retourner à la liste</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

src/Web/ModernRecrut.MVC/Views/Notes/Index.cshtml
@model IEnumerable<ModernRecrut.MVC.Models.Postulation>


@{
    ViewData["Title"] = "Index";
}

<h1>Liste des postulations </h1>
@using (Html.BeginForm("MesNotes", "Notes", FormMethod.Get))
{
    <button class="btn btn-primary btn-sm">Mes notes</button>
}

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.OffreEmploi.Poste)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PretentionSalariale)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Candidat.Nom) 
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateDisponibilite)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.OffreEmploi.Poste)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PretentionSalariale)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Candidat.Prenom) @Html.DisplayFor(modelItem => item.Candidat.Nom)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DateDisponibilite)
                </td>
                <td>
                    <a asp-action="Create" class="btn btn-secondary btn-sm" asp-route-id="@item.Id">Ajouter une note</a>
                    <a asp-action="Details" asp-controller="Postulations" class="btn btn-secondary btn-sm" asp-route-id="@item.Id">Détails de la postulation</a>
                </td>
                
            </tr>
        }
    </tbody>
</table>

src/Web/ModernRecrut.MVC/Views/Notes/MesNotes.cshtml
@model IEnumerable<ModernRecrut.MVC.Models.Note>


@{
    ViewData["Title"] = "Index";
}

<h1>Liste de mes notes </h1>


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NomEmetteur)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PostulationID)
            </th>
            
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NomEmetteur)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PostulationID)
                </td>
              
                <td>
                    <a asp-action="Delete" class="btn btn-secondary btn-sm" asp-route-id="@item.Id">Supprimer</a>
                    <a asp-action="Edit" class="btn btn-secondary btn-sm" asp-route-id="@item.Id">Modifier</a>
					<a asp-action="Details" class="btn btn-secondary btn-sm" asp-route-id="@item.Id">Détails</a>
            </tr>
        }
    </tbody>
</table>